import { writeFileSync, readFileSync } from 'node:fs';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const src = readFileSync('gcal_test.mjs', 'utf8');
const FAKE = eval('`' + src.slice(src.indexOf('const FAKE = `') + 14, src.indexOf('})();`;') + 5) + '`');
const t = await fetch('http://127.0.0.1:9333/json/new?about:blank', { method: 'PUT' }).then(r => r.json());
const ws = new WebSocket(t.webSocketDebuggerUrl); await new Promise(r => ws.addEventListener('open', r));
let id = 0; const pending = new Map();
ws.addEventListener('message', e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = expr => send('Runtime.evaluate', { expression: `(async () => { ${expr} })()`, awaitPromise: true, returnByValue: true });
await send('Page.enable');
await send('Page.addScriptToEvaluateOnNewDocument', { source: FAKE });
await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: true });
await send('Page.navigate', { url: 'http://localhost:5500/' }); await sleep(1500);
const S = 'https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events';
await ev(`localStorage.setItem('ple-gcal-extra', JSON.stringify({ 'work@company.com': { token: 'fakeExtra', exp: Date.now() + 3600e3, scope: '${S}' } })); localStorage.setItem('ple-theme','"light"'); return 1`);
await send('Page.reload'); await sleep(2500);
await ev(`document.getElementById('menuBtn').click(); await new Promise(r => setTimeout(r, 600)); const b = document.querySelector('#menuModal .modal-box'); b.scrollTop = document.querySelector('.gcal-slot').offsetTop - 40; return 1`);
await sleep(500);
let r = await send('Page.captureScreenshot', { format: 'png' }); writeFileSync('shot-gcal-menu.png', Buffer.from(r.result.data, 'base64'));
await ev(`history.back(); await new Promise(r => setTimeout(r, 600)); document.querySelector('.cell.today').click(); await new Promise(r => setTimeout(r, 600)); document.querySelector('#dayPanel .event-add').open = true; return 1`);
await sleep(500);
r = await send('Page.captureScreenshot', { format: 'png' }); writeFileSync('shot-gcal-panel.png', Buffer.from(r.result.data, 'base64'));
ws.close(); process.exit(0);
