const sleep = ms => new Promise(r => setTimeout(r, ms));
const tabs = await fetch('http://127.0.0.1:9333/json').then(r => r.json());
const tab = tabs.find(t => t.url.includes('localhost:5500'));
const ws = new WebSocket(tab.webSocketDebuggerUrl); await new Promise(r => ws.addEventListener('open', r));
let id = 0; const pending = new Map();
ws.addEventListener('message', e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const r = await send('Runtime.evaluate', { expression: `(async () => { const g = await import('/js/sync/gcal.js'); const go = await import('/js/sync/google.js'); const tok = JSON.parse(localStorage.getItem('ple-gtoken')||'null'); return JSON.stringify({ st: g.getStatus(), hasToken: go.hasToken(), tokExp: tok && (tok.exp - Date.now()), fakeFail: __fakeDb().fail, extra: Object.keys(JSON.parse(localStorage.getItem('ple-gcal-extra')||'{}')) }); })()`, awaitPromise: true, returnByValue: true });
console.log(r.result?.result?.value || JSON.stringify(r).slice(0, 400));
ws.close(); process.exit(0);
