import { writeFileSync } from 'node:fs';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const target = await fetch('http://127.0.0.1:9333/json/new?about:blank', { method: 'PUT' }).then(r => r.json());
const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(r => ws.addEventListener('open', r));
let id = 0; const pending = new Map();
ws.addEventListener('message', e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = async expr => (await send('Runtime.evaluate', { expression: expr, awaitPromise: true, returnByValue: true })).result?.result?.value;
const shot = async name => { await sleep(600); const r = await send('Page.captureScreenshot', { format: 'png' }); writeFileSync('shots/' + name, Buffer.from(r.result.data, 'base64')); };
const size = (w, h, mobile) => send('Emulation.setDeviceMetricsOverride', { width: w, height: h, deviceScaleFactor: 1, mobile });
await send('Page.enable');
await size(390, 844, true);
await send('Page.navigate', { url: 'http://localhost:5500/' }); await sleep(2000);
await ev(`localStorage.clear(); localStorage.setItem('ple-theme','"light"')`);
await send('Page.reload'); await sleep(1500);
await shot('m1-home.png');
await ev(`document.querySelector('#menuBtn').click()`);
await shot('m2-menu-top.png');
await ev(`document.querySelector('#menuModal [data-mode="auto"]').click(); document.querySelector('#menuModal .sync-card').scrollIntoView({ block: 'start' })`);
await shot('m3-menu-sync.png');
await ev(`document.querySelector('#menuModal .side-backup').scrollIntoView({ block: 'end' })`);
await shot('m4-menu-backup.png');
await ev(`document.querySelector('#menuModal [data-screen="ledger"]').click()`);
await shot('m5-ledger-empty.png');
await ev(`document.querySelector('[data-tab="tasks"]').click()`);
await shot('m6-tasks-empty.png');
await size(1280, 800, false);
await ev(`localStorage.setItem('ple-theme','"dark"')`); await send('Page.reload'); await sleep(1500);
await ev(`document.querySelector('#menuBtn').click()`);
await shot('m7-desktop-dark-menu.png');
ws.close(); process.exit(0);
