import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
const OUT = process.argv[2];
const sleep = ms => new Promise(r => setTimeout(r, ms));
const target = await fetch('http://127.0.0.1:9333/json/new?about:blank', { method: 'PUT' }).then(r => r.json());
const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(r => ws.addEventListener('open', r));
let id = 0; const pending = new Map();
ws.addEventListener('message', e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const evalJs = async expr => (await send('Runtime.evaluate', { expression: expr, awaitPromise: true, returnByValue: true })).result?.result;
const shot = async name => { await sleep(500); const r = await send('Page.captureScreenshot', { format: 'png' }); writeFileSync(join(OUT, name), Buffer.from(r.result.data, 'base64')); };

await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 1700, deviceScaleFactor: 1, mobile: true });
await send('Page.navigate', { url: 'http://localhost:5500/' });
await sleep(2000);
await evalJs(`localStorage.clear(); localStorage.setItem('ple-tab', '"ledger"'); localStorage.setItem('ple-theme', '"light"')`);
await send('Page.reload'); await sleep(1500);
console.log(JSON.stringify(await evalJs(`(async () => {
  const { saveRule } = await import('/js/recurring.js');
  saveRule({ type: 'income', memo: '월급', category: 'salary', amount: 3200000, askAmount: false, day: '25' });
  saveRule({ type: 'expense', memo: '월세', category: 'living', amount: 550000, askAmount: false, day: '1' }, { includeThisMonth: true });
  saveRule({ type: 'expense', memo: '통신비', category: 'living', amount: 45000, askAmount: false, day: 'last' });
  saveRule({ type: 'expense', memo: '전기요금', category: 'living', amount: null, askAmount: true, day: '2' }, { includeThisMonth: true });
  return 'seeded';
})()`)));
await sleep(500);
await shot('rec-mobile-ledger.png');
await evalJs(`document.querySelector('.rule-row').click()`);
await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
await shot('rec-mobile-editor.png');
await evalJs(`document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))`);
await evalJs(`localStorage.setItem('ple-theme', '"dark"')`);
await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 1500, deviceScaleFactor: 1, mobile: false });
await send('Page.reload'); await sleep(1500);
await shot('rec-desktop-dark-ledger.png');
ws.close();
process.exit(0);
