import { readFileSync, writeFileSync } from 'node:fs';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const S1 = readFileSync('gcal_test.mjs', 'utf8');
const FAKE_CAL = eval('`' + S1.slice(S1.indexOf('const FAKE = `') + 14, S1.indexOf('})();`;') + 5) + '`').replaceAll('me@gmail.com', 'damda.demo@gmail.com');
const M = readFileSync('menu_test.mjs', 'utf8');
const FAKE_DG = eval('`' + M.slice(M.indexOf('const FAKE_DRIVE_GIS = `') + 24, M.indexOf('})();`;', M.indexOf('const FAKE_DRIVE_GIS')) + 5) + '`');
const t = await fetch('http://127.0.0.1:9333/json/new?about:blank', { method: 'PUT' }).then(r => r.json());
const ws = new WebSocket(t.webSocketDebuggerUrl); await new Promise(r => ws.addEventListener('open', r));
let id = 0; const pending = new Map();
ws.addEventListener('message', e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = expr => send('Runtime.evaluate', { expression: `(async () => { ${expr} })()`, awaitPromise: true, returnByValue: true });
await send('Page.enable'); await send('Network.enable'); await send('Network.setCacheDisabled', { cacheDisabled: true }); await send('Network.setBypassServiceWorker', { bypass: true });
await send('Page.addScriptToEvaluateOnNewDocument', { source: FAKE_CAL });
await send('Page.addScriptToEvaluateOnNewDocument', { source: FAKE_DG });
await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 800, deviceScaleFactor: 1, mobile: false });
await send('Page.navigate', { url: 'http://localhost:5500/' }); await sleep(1200);
await ev(`localStorage.clear(); localStorage.setItem('ple-theme','"light"'); localStorage.setItem('ple-google', JSON.stringify({ email: 'damda.demo@gmail.com' })); localStorage.setItem('ple-gtoken', JSON.stringify({ token: 'fakeMain', exp: Date.now() + 3600e3, scope: 'https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events' })); return 1`);
await send('Page.reload'); await sleep(3000);
await ev(`document.getElementById('menuBtn').click(); await new Promise(r => setTimeout(r, 500)); document.querySelector('[data-act="open-settings"]').click(); await new Promise(r => setTimeout(r, 600)); return 1`);
const r = await send('Page.captureScreenshot', { format: 'png' }); writeFileSync('shot-settings.png', Buffer.from(r.result.data, 'base64'));
ws.close(); process.exit(0);
