import { writeFileSync } from 'node:fs';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const target = await fetch('http://127.0.0.1:9333/json/new?about:blank', { method: 'PUT' }).then(r => r.json());
const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(r => ws.addEventListener('open', r));
let id = 0; const pending = new Map();
ws.addEventListener('message', e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = async expr => (await send('Runtime.evaluate', { expression: expr, awaitPromise: true, returnByValue: true })).result?.result?.value;
const shot = async name => { await sleep(700); const r = await send('Page.captureScreenshot', { format: 'png' }); writeFileSync('shots/' + name, Buffer.from(r.result.data, 'base64')); };
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
await send('Page.navigate', { url: 'http://localhost:5500/' }); await sleep(2000);
await ev(`localStorage.clear(); localStorage.setItem('ple-theme','"light"')`);
await send('Page.reload'); await sleep(1500);
await shot('s1-calendar.png');
await ev(`document.querySelector('#menuBtn').click()`);
await ev(`document.querySelector('#menuModal .sync-card').scrollIntoView({ block: 'start' })`);
await shot('s2-menu-sync.png');
await ev(`document.querySelector('#menuModal [data-screen="tasks"]')?.click()`);
await shot('s3-tasks.png');
// 연결된 뒤 로그인이 만료된 모습 (가짜 계정 표시)
await ev(`localStorage.setItem('ple-google', JSON.stringify({ email: 'me@gmail.com' })); localStorage.setItem('ple-sync-mode', '"auto"'); localStorage.setItem('ple-sync-state', JSON.stringify({ lastSync: Date.now() - 180000 }))`);
await send('Page.reload'); await sleep(1500);
await ev(`document.querySelector('#menuBtn').click()`);
await ev(`document.querySelector('#menuModal .sync-card').scrollIntoView({ block: 'start' })`);
await shot('s4-menu-relogin.png');
ws.close(); process.exit(0);
