import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
const OUT = process.argv[2];
const sleep = ms => new Promise(r => setTimeout(r, ms));
const target = await fetch('http://127.0.0.1:9333/json/new?about:blank', { method: 'PUT' }).then(r => r.json());
const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(r => ws.addEventListener('open', r));
let id = 0; const pending = new Map();
ws.addEventListener('message', e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const evalJs = async expr => (await send('Runtime.evaluate', { expression: expr, awaitPromise: true, returnByValue: true })).result?.result;
const shot = async name => { await sleep(500); const r = await send('Page.captureScreenshot', { format: 'png' }); writeFileSync(join(OUT, name), Buffer.from(r.result.data, 'base64')); };
const size = (w, h, mobile) => send('Emulation.setDeviceMetricsOverride', { width: w, height: h, deviceScaleFactor: 1, mobile });
const go = async (theme, tab) => { await evalJs(`localStorage.setItem('ple-theme','"${theme}"'); localStorage.setItem('ple-tab','"${tab}"')`); await send('Page.reload'); await sleep(1500); };

await send('Page.enable');
await size(390, 844, true);
await send('Page.navigate', { url: 'http://localhost:5500/' });
await sleep(2000);
await evalJs(`localStorage.clear()`);
await send('Page.reload'); await sleep(1500);
console.log(JSON.stringify(await evalJs(`(async () => {
  const { addCategory } = await import('/js/categories.js');
  const { store } = await import('/js/store.js');
  const { saveRule } = await import('/js/recurring.js');
  const { todayKey } = await import('/js/utils.js');
  const w = addCategory('task', '업무', { slot: 1 }), h = addCategory('task', '운동', { slot: 3 }), s = addCategory('task', '공부', { slot: 0 });
  addCategory('task', '집안일', { slot: 5 });
  const k = todayKey();
  store.put('tasks', { date: k, title: '프로젝트 기획서 검토', category: w.id, done: true });
  store.put('tasks', { date: k, title: '헬스 1시간', category: h.id, done: false });
  store.put('tasks', { date: k, title: '영어 단어 30개', category: s.id, done: false });
  saveRule({ type: 'income', memo: '월급', category: 'salary', amount: 3200000, askAmount: false, day: '25' });
  saveRule({ type: 'expense', memo: '월세', category: 'living', amount: 550000, askAmount: false, day: '1' }, { includeThisMonth: true });
  saveRule({ type: 'expense', memo: '관리비', category: 'living', amount: null, askAmount: true, day: '2' }, { includeThisMonth: true });
  const r = saveRule({ type: 'expense', memo: '통신비', category: 'living', amount: 45000, askAmount: false, day: 'last' });
  store.put('recurring', { id: r.id, paused: true });
  return 'seeded';
})()`)));
for (const theme of ['light', 'dark']) {
  await size(390, 2300, true); await go(theme, 'ledger'); await shot(`v2-mobile-${theme}-ledger.png`);
  await size(390, 1000, true); await go(theme, 'tasks'); await shot(`v2-mobile-${theme}-tasks.png`);
}
await size(390, 1000, true); await go('light', 'ledger');
await evalJs(`document.querySelector('.rule-card [data-act="add-rule"]').click()`); await sleep(300);
await evalJs(`[...document.querySelectorAll('#recurringModal [data-pick]')].find(b => b.textContent.includes('월급')).click()`);
await shot('v2-mobile-light-editor.png');
await evalJs(`document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))`); await sleep(300);
await go('light', 'tasks');
await evalJs(`document.querySelector('#menuBtn').click()`); await sleep(200);
await evalJs(`document.querySelector('#menuModal [data-act="cat-ledger"]').click()`); await sleep(300);
await shot('v2-mobile-light-manager.png');
await size(1280, 1000, false); await go('dark', 'calendar');
await evalJs(`document.querySelector('.cell.today').click()`);
await shot('v2-desktop-dark-panel.png');
ws.close(); process.exit(0);
