import fs from 'fs';
const t = (await (await fetch('http://127.0.0.1:9334/json')).json()).find(t => t.url.startsWith('http://localhost:5500/') && !t.url.includes('__damda'));
const ws = new WebSocket(t.webSocketDebuggerUrl); await new Promise(r => ws.onopen = r);
let id = 0; const wait = new Map(); ws.onmessage = m => { const d = JSON.parse(m.data); wait.get(d.id)?.(d); };
const send = (method, params = {}) => new Promise(r => { const i = ++id; wait.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = async e => { const r = (await send('Runtime.evaluate', { expression: e, returnByValue: true, awaitPromise: true })).result; if (r?.exceptionDetails) console.log('오류', r.exceptionDetails.exception?.description); return r?.result?.value; };
const sleep = ms => new Promise(r => setTimeout(r, ms));
const shot = async n => { const r = await send('Page.captureScreenshot', { format: 'png' }); fs.writeFileSync(n, Buffer.from(r.result.data, 'base64')); };
const ok = (n, c) => console.log(c ? '✅' : '❌', n);
await send('Runtime.enable');
ok('오른쪽 탭 3개', await ev(`[...document.querySelectorAll('.desk-tabs button')].map(b => b.textContent).join('|') === '이 날|할 일|가계부'`));
ok('처음엔 [이 날] + 오늘 패널', await ev(`document.querySelector('.desk-tabs .on')?.textContent === '이 날' && !document.getElementById('dayPanel').hidden`));
await shot('shot-side-day.png');
await ev(`document.querySelector('.desk-tabs [data-screen="tasks"]').click()`); await sleep(500);
ok('[할 일] 탭: 할 일 화면 보이고 캘린더도 보임', await ev(`!document.getElementById('view-tasks').hidden && !document.getElementById('view-calendar').hidden && document.getElementById('dayPanel').hidden`));
await shot('shot-side-tasks.png');
await ev(`document.querySelector('.desk-tabs [data-screen="ledger"]').click()`); await sleep(500);
ok('[가계부] 탭', await ev(`!document.getElementById('view-ledger').hidden && document.getElementById('view-tasks').hidden`));
await shot('shot-side-ledger.png');
await ev(`document.querySelectorAll('#view-calendar .cell')[15].click()`); await sleep(500);
ok('가계부 보다가 날짜 누르면 [이 날]로', await ev(`document.querySelector('.desk-tabs .on')?.textContent === '이 날' && !document.getElementById('dayPanel').hidden && document.getElementById('view-ledger').hidden`));
await ev(`document.getElementById('menuBtn').click()`); await sleep(400);
ok('메뉴를 열어도 오른쪽 [이 날]이 안 닫힘', await ev(`!document.getElementById('dayPanel').hidden`));
await ev(`document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))`); await sleep(300);
await ev(`document.querySelector('#view-calendar .cell.today').click()`); await sleep(300);
// 할 일 넣기 → 캘린더 칸에 바로
const before = await ev(`document.querySelector('#view-calendar .cell.today').innerText`);
await ev(`(() => { const i = document.querySelector('#dayPanel .task-input'); i.value = '오른쪽에서 넣은 할 일'; i.closest('form').requestSubmit(); })()`); await sleep(600);
const after = await ev(`document.querySelector('#view-calendar .cell.today').innerText`);
ok('[이 날]에서 넣은 할 일이 왼쪽 캘린더 칸에 바로 반영', before !== after);
const errs = await ev(`window.__errs?.length ?? 0`);
ws.close();
